language: python
dist: xenial
python:
- '2.7'
- '3.5'
- '3.6'
env:
- DJANGO="Django>=1.11,<1.12.0"
- DJANGO="Django>=2.2,<2.3"
- DJANGO="Django>=3.0,<3.1"
matrix:
  exclude:
  - python: '2.7'
    env: DJANGO="Django>=2.0,<2.1"
  - python: '2.7'
    env: DJANGO="Django>=2.2,<2.3"
  - python: '2.7'
    env: DJANGO="Django>=3.0,<3.1"
  - python: '3.5'
    env: DJANGO="Django>=3.0,<3.1"
install:
- pip install -q $DJANGO
- pip install -q -r test_reqs.txt
- pip install coveralls
script:
- python runtests.py
- flake8 djangowind *.py
- coverage run --source=djangowind runtests.py
after_success:
- coveralls
