language: python
sudo: false
python:
- '2.7'
- '3.5'
env:
- DJANGO="Django>=1.8.0,<1.9.0"
- DJANGO="Django>=1.10,<1.11.0"
- DJANGO="Django>=1.11,<1.12.0"
install:
- pip install -q $DJANGO
- pip install -q -r test_reqs.txt
- pip install coveralls
script:
- python runtests.py
- flake8 djangowind --max-complexity=12
- coverage run --source=djangowind runtests.py
after_success:
- coveralls
notifications:
  slack: ccnmtl:GizSNscLWJLldjQrffB8mwgm
deploy:
  provider: pypi
  user: ctlpypi
  password:
    secure: K9YZJBFyFxQhlE221Pgzv9EoMEYmiy21ieRYHwcndKq5P8BJX47qPxHz4JE1lqUb8H3+3p2Bzlaw3epccYrnoYfuGqRpfkKJ3TbbyBIhwHdpV/9P7en4KOb4YSgQidJHwu1ogXYXXuexrvqXtg94OZhUThVKiO6tXumkAum/fqQ=
  on:
    tags: true
    distributions: sdist bdist_wheel
    repo: ccnmtl/djangowind
