language: python
sudo: false
python:
  - "2.7"
env:
  - DJANGO="Django>=1.8.0,<1.9.0"
  - DJANGO="Django>=1.9.0,<1.10.0"

# command to install dependencies
install:
  - pip install -q $DJANGO --use-mirrors
  - pip install -q -r test_reqs.txt --use-mirrors
  - pip install coveralls

# command to run tests
script:
  - python runtests.py
  - flake8 djangowind
  - coverage run --source=djangowind runtests.py
after_success:
  - coveralls
notifications:
  slack: ccnmtl:GizSNscLWJLldjQrffB8mwgm
