language: python
dist: bionic
python:
- '3.6'
- '3.8'
env:
- DJANGO="Django>=2.2,<2.3"
- DJANGO="Django>=3.1,<3.2"
install:
- pip install -q $DJANGO
- pip install -q -r test_reqs.txt
- pip install coveralls
script:
- python runtests.py
- flake8 djangowind *.py
- coverage run --source=djangowind runtests.py
after_success:
- coveralls
